[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-pc-windows-gnu",
]
all-features = true

[licenses]
version = 2
allow = [
    "0BSD",
    "Apache-2.0",
    "MIT",
    "Unlicense",
    "Zlib",
    "MPL-2.0"
]

exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []